/*
 * This file was generated by the Gradle "init" task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.3.3/samples
 */
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
    java
    idea
    application
    id("com.github.johnrengelman.shadow") version "7.1.2"
    id("io.freefair.lombok") version "6.3.0"

}

group "com.tomasguinzburg.demo.transactions"
version "0.0.1-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    annotationProcessor("com.google.dagger:dagger-compiler:2.40.5")
    annotationProcessor("org.projectlombok:lombok:1.18.22")
    compileOnly("org.projectlombok:lombok:1.18.22")
    implementation("com.google.dagger:dagger:2.40.5")
    implementation("com.sparkjava:spark-core:2.9.3")
    implementation("org.slf4j:slf4j-simple:1.7.35")
    implementation("junit:junit:4.13.2")
    implementation("com.google.code.gson:gson:2.8.9")
    implementation("com.google.guava:guava:31.0.1-jre")                     //For more collectors
    testAnnotationProcessor("com.google.dagger:dagger-compiler:2.40.5")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.22")
    testCompileOnly("org.projectlombok:lombok:1.18.22")
    testImplementation("com.google.dagger:dagger:2.40.5")
    testImplementation("com.sparkjava:spark-core:2.9.3")
    testImplementation("org.slf4j:slf4j-simple:1.7.35")
    testImplementation("junit:junit:4.13.2")
    testImplementation("com.google.code.gson:gson:2.8.9")
}


java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
    withSourcesJar()
}

application() {
    mainClass.set("com.tomasguinzburg.demo.impl.application.App")
}
